title: Federal website standards
email: website.standards@gsa.gov
description: >- # this means to ignore newlines
  Federal website standards will help agencies provide high-quality, consistent digital experiences for everyone.


hosts:
  # This should be changed to https://standards.digital.gov when the site transitions
  prod: https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov
  sandbox: https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov

# Configuration for the Digital Analytics Program
dap:
  agency: GSA

  # Optional
  subagency: TTS

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: Standards
    url: /standards/
  - name: About
    url: /about/
  - name: Contact
    url: /contact/
# secondary_navigation:
#   - name: Secondary link
#     url: "#main-content"
#   - name: Another secondary link
#     url: "#main-content"

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.

searchgov:
  # Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
  endpoint: https://search.usa.gov

  # Replace this with your search.gov account.
  affiliate: website-standards

  # Replace this with your access key.
  access_key: -EqFgr2b55x2dqE_-WLcdPLwblpkBeJRDlJFFuoFrkM=

  # This renders the results within the page instead of sending the user to search.gov.
  inline: true

  # This allows Search.gov to present relevant type-ahead search suggestions in your website's search box.
  # If you do not want to present search suggestions, set this value to false.
  suggestions: true
##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################
